export const HARDWARE_ITEMS = [
  'Austausch und Fetten der material pump tubes',
  'Austausch und Fetten der roller pump tubes',
  'Austausch und Fetten der waste pump tube',
  'Austausch und Fetten der vacuum pump tube',
  'Austausch der roller waste collector tubes',
  'Austausch des vacuum filter',
  'Austausch der wiper base',
  'Kontrollieren des Wiper Antriebs',
  'Fetten der Z-axis screws',
  'Austausch der grind wheels und Säuberung des build tray wheel track',
  'Überprüfen der build-tray belt tension',
  'Überprüfen, dass das UV module sauber ist',
  'Überprüfen des roller-waste collector, wenn nötig austauschen',
  'Überprüfen, dass das material cabinet board sauber ist',
  'Überprüfen, dass die Lüfter funktionieren',
  'Austausch des ProAero pre filter, wenn nötig (Vorfiltermatte, weiß)',
  'Austausch leerer Kartuschen',
];

export const SOFTWARE_ITEMS = [
  'Kalibrierung des wipers',
  'Ausführen des Vacuum Calibration wizard',
  'Ausführen des Head-filling wizard',
  'Ausführen des Head-purging wizard',
  'Ausführen des Advanced Head Optimization wizard',
  'Zurücksetzen des PM counter bei Nutzung des Preventive Maintenance wizard',
  'Ausführen des Weight sensor calibration wizard',
  'Testdruck mit Wartungswürfel.stl starten',
];
